<header>
            <div class="container">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <Brand and toggle get grouped for better mobile display>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span><!--a href="lien1.html"></a-->
           <span class="icon-bar"><!--lien 2</span><a href="contact.php"></a> 
           <span class="icon-bar">lien 3</span--> 
        </button>
        <a class="navbar-brand" href="#"><!--Brand</-->
      </div>
      <div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a:link{color:#265301;} href="formations.php">Mes formations</a>
  <a class="text-white" href="exp_pro.php">Carrière</a>
  <a class="text-white" href="formations.php">Formations</a>
  <a class="text-white" href="loisir.php">Running</a>
  <a class="text-white" href="contact.php">Contact</a>
  <!--p style="color:#14A44D; ">Carrière2<a href="exp_pro.php"</a-->
</div>
        </header>